version:                   "3.3"
services:
  db:
    image:                 mysql:5.7
    restart:               always
    environment:
      MYSQL_DATABASE:      "badb"
      MYSQL_USER:          "user"
      MYSQL_PASSWORD:      "1234567890"
      MYSQL_ROOT_PASSWORD: "1234567890"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - baDbVolume:/var/lib/mysql
volumes:
  baDbVolume:
